apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-bot
spec:
  selector:
    matchLabels:
      app: label-bot
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: label-bot
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: workingnode
      #           operator: In
      #           values: ["true"]
      containers:
      - name: label-bot
        image: quzicheng/label-bot:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        env:
        - name: api_url
          value: "http://data-cache/api/dataCache/pushGiteeIssue"
        volumeMounts:
          - name: log-volume
            #mountPropagation: "Bidirectional"
            mountPath: "/app/src/log/"

      volumes:
      - name: log-volume
        hostPath:
          path: /event-platform-nfs/prod/label-bot-log
          type: DirectoryOrCreate